import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import desktop from '../public/assets/desktop.png'
import logo from '../public/assets/logo.png'
import styled from '@emotion/styled'
import Cart from './composants/Cart';
import axians from '../public/assets/icons/axians.png'
import Menu from './Menu';
import Carousel from './composants/Carousel';


export default function Apropos() {

  const [isChange, setChange] = useState(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio | William Quesnot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <section className={styles.center} style={{height : '100vh', width :'100%'}}>
        <div style={{display : 'flex', alignItems : 'center', flexDirection : 'column', height : '100%'}}>
        <h2 style={{color : 'rgb(73, 242, 202)'}}>À PROPOS DE MOI</h2>

        {isChange ?(
                <div>
        <div style={{display : 'flex', alignItems : 'center', justifyContent : 'center'}}>
                    <button style={{ backgroundColor : 'rgb(73, 242, 202)', border : 'none', padding : '1em 2em', width : '170px', height : '50px', display : 'flex', alignItems : 'center', justifyContent :' center', marginRight : '0.5em', cursor : 'pointer'}}><h3>Mes informations</h3></button>
                    <button onClick={()=> setChange(false)} style={{ cursor : 'pointer',backgroundColor : 'transparent', color : 'rgb(73, 242, 202)', border : '1px solid rgb(73, 242, 202) ', padding : '1em 2em', width : '170px', height : '50px', display : 'flex', alignItems : 'center', justifyContent : 'center', marginLeft : '0.5em'}}><h3>Comment je procède</h3></button>
                </div>

              <p style={{padding : '1em', textAlign : 'justify'}}>Je suis William Quesnot. J&apos;ai fait un bac scientifique. Ensuite, j&apos;ai suivi une formation Google à distance en marketing digital et j&apos;ai obtenu le diplôme Les fondamentaux du Marketing Digital.<br/><br/>

Passionné par les nouvelles technologies et l&apos;informatique, j&apos;ai appris en autodidacte le langage de programmation JavaScript, souvent utilisé dans les pages web interactives. Par la suite je l&apos;ai combiné avec les technologies HTML et CSS pour faire du développement web.<br/><br/>
Je suis actuellement en école d&apos;ingénieur en informatique pour parfaire mes connaissances et mes compétences. <br/><br/>

Je suis motivé et curieux d&apos;apprendre de nouvelles choses. Je souhaite développer mes connaissances et mes compétences afin de les mettre en pratique dans divers projets et accomplir mes objectifs professionnels.</p></div>
            
            ):(
                <div>
                     <div style={{display : 'flex', alignItems : 'center', justifyContent : 'center'}}>
                        <button onClick={()=> setChange(true)} style={{ cursor : 'pointer',backgroundColor : 'transparent', color : 'rgb(73, 242, 202)', border : '1px solid rgb(73, 242, 202)', padding : '1em 2em', width : '170px', height : '50px', display : 'flex', alignItems : 'center', justifyContent :' center', marginRight : '0.5em'}}><h3>Mes informations</h3></button>
                        <button style={{ cursor : 'pointer',backgroundColor : 'rgb(73, 242, 202)', border : 'none', padding : '1em 2em', width : '170px', height : '50px', display : 'flex', alignItems : 'center', justifyContent : 'center', marginLeft : '0.5em'}}><h3>Comment je procède</h3></button>
                    </div>
                    
              
                    <div style={{display : 'flex', alignItems : 'center', justifyContent : 'center', marginTop : '2.5em'}}>
                        
                        <Carousel />
                    </div>
                    <div style={{display : 'flex', justifyContent : 'space-between', alignItems : 'center'}}>
                        <p style={{color : 'grey', textAlign : 'center', fontSize : '0.8em'}}>Glisse vers la gauche</p>
                        <p style={{color : 'grey', textAlign : 'center', fontSize : '0.8em'}}>Glisse vers la droite</p>
                    </div>

                    
                    
                </div>
            )}
         
          
        </div>
      </section>

    </div>
  )
}
