import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import logo from '../public/assets/logo.png'
import html from '../public/assets/icons/html.svg'
import css from '../public/assets/icons/css.svg'
import js from '../public/assets/icons/js.svg'
import ts from '../public/assets/icons/ts.png'
import mysql from '../public/assets/icons/mysql.svg'
import mongodb from '../public/assets/icons/mongodb.png'
import firebase from '../public/assets/icons/firebase.webp'
import react from '../public/assets/icons/reacticon.png'
import Menu from './Menu';
import { useState } from 'react';




export default function Competences() {

  

  const [isSkills, setIsSkills] = useState(true);


  return isSkills ? (
    <div className={styles.container}>
      <Head>
        <title>Portfolio | William Quesnot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />


      <section className={styles.center} style={{height : '100vh', width :'100%', marginBottom : '5em'}}>
        <div style={{display : 'flex', alignItems : 'center', flexDirection : 'column'  , height : '100%'}}>
          <h2 style={{color : 'rgb(73, 242, 202)'}}>MES COMPÉTENCES</h2>


          { isSkills ?(
            <section>
                <div style={{display : 'flex', alignItems : 'center', justifyContent : 'center'}}>
                    <button style={{ backgroundColor : 'rgb(73, 242, 202)', border : 'none', padding : '1em 2em', width : '190px', height : '50px', display : 'flex', alignItems : 'center', justifyContent :' center', marginRight : '0.5em', cursor : 'pointer'}}><h3>Compétences principales</h3></button>
                    <button onClick={()=> setIsSkills(false)} style={{ cursor : 'pointer',backgroundColor : 'transparent', color : 'rgb(73, 242, 202)', border : '1px solid rgb(73, 242, 202) ', padding : '1em 2em', width : '190px', height : '50px', display : 'flex', alignItems : 'center', justifyContent : 'center', marginLeft : '0.5em'}}><h3>Compétences complémentaires</h3></button>
                </div>
                <div>
                    <h3>FRONT-END</h3>
                    <div style={{display : 'flex', justifyContent : 'space-around'}}>
                        <Image src={html} alt="html" width={50} />
                        <Image src={css} alt="css" width={50} />
                        <Image src={js} width={50} alt="js" />
                        <Image src={ts} width={50} alt="ts" />
                    </div>
                </div>
                <div>
                    <h3>BACK-END</h3>
                    <div style={{display : 'flex', justifyContent : 'space-around'}}>
                        <Image src={js} width={50} alt="js" />
                    </div>
                </div>
                <div>
                    <h3>BASE DE DONNÉES</h3>
                    <div style={{display : 'flex', justifyContent : 'space-around', alignItems : 'center'}}>
                        <Image src={mysql} width={80} alt="mysql" />
                        <Image src={mongodb} width={80} alt="mongodb"/>
                        <Image src={firebase} width={80} alt="firebase" />
                    </div>
                </div>
                <div>
                    <h3>FRAMEWORKS</h3>
                    <div style={{display : 'flex', justifyContent : 'space-around'}}>
                        <Image src={react} width={50} alt="react" />
                    </div>
                </div>
            </section>
          ):
          (
            <section>
                <div style={{display : 'flex', alignItems : 'center', justifyContent : 'center'}}>
                    <button onClick={()=> setIsSkills(true)} style={{ cursor : 'pointer',backgroundColor : 'transparent', color : 'rgb(73, 242, 202)', border : '1px solid rgb(73, 242, 202)', padding : '1em 2em', width : '190px', height : '50px', display : 'flex', alignItems : 'center', justifyContent :' center', marginRight : '0.5em'}}><h3>Compétences principales</h3></button>
                    <button style={{ cursor : 'pointer',backgroundColor : 'rgb(73, 242, 202)', border : 'none', padding : '1em 2em', width : '190px', height : '50px', display : 'flex', alignItems : 'center', justifyContent : 'center', marginLeft : '0.5em'}}><h3>Compétences complémentaires</h3></button>
                </div>
            </section>
          )}
           
           
          
        </div>
      </section>

    </div>
  ):(
    <div>ok</div>
  )
}


