import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import desktop from '../public/assets/desktop.png'
import logo from '../public/assets/logo.png'
import styled from '@emotion/styled'
import Cart from './composants/Cart';
import axians from '../public/assets/icons/axians.png'
import Menu from './Menu';


export default function Contact() {

  
  



  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio | William Quesnot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <section className={styles.center} style={{height : '100vh', width :'100%'}}>
        <div style={{display : 'flex', alignItems : 'center', flexDirection : 'column', height : '100%'}}>
        <h2 style={{color : 'rgb(73, 242, 202)'}}>ME CONTACTER </h2>

        <p>Comment me contacter ?</p>
        <p>C&apos;est tout simple ! Envoie moi un mail sur mon <br/> adresse : </p>
        <div style={{width :'310px', height : '50px', border : '1px solid rgb(73, 242, 202)', display : 'flex', alignItems : 'center', justifyContent : 'center', marginTop : '2em'}}>
                <a href="google.com">quesnot.william@hotmail.com</a>
              </div>
          
            
          
        </div>
      </section>

    </div>
  )
}
