import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import desktop from '../public/assets/desktop.png'
import logo from '../public/assets/logo.png'
import styled from '@emotion/styled'
import Menu from './Menu';



export default function Home() {

  



  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio | William Quesnot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <section className={styles.center} style={{height : '100vh', width :'100%'}}>
        <div style={{display : 'flex', alignItems : 'center', flexDirection : 'column', height : '100%', marginTop :'2em'}}>
          <Animation>
            <Image className="desktop" alt="bg desktop" src={desktop} width={150} />
          </Animation>
          <div>
            <h2 style={{color :'rgb(73, 242, 202)', fontSize : '2em', fontFamily : 'monospace'}}>Je suis William,</h2>
            <h1 style={{fontSize : '2.2em'}}>DÉVELOPPEUR <br/><b style={{fontWeight : 'lighter'}}>FRONT-END</b></h1>

            <div style={{width : '100%', textAlign : 'center'}}>
              <div style={{width :'310px', height : '50px', border : '1px solid rgb(73, 242, 202)', display : 'flex', alignItems : 'center', justifyContent : 'center'}}>
                <a href="google.com">quesnot.william@hotmail.com</a>
              </div>
            </div>
            <br/>
            

            <div style={{textAlign : 'center'}}>
              <h3>J&apos;offre mes services pour intégrer <br/> l&apos;<b style={{color : 'rgb(73,242,202'}}>interface</b>, le <b style={{ color : 'rgb(73, 242, 202)'}}>design</b> et le <b style={{color : 'rgb(73, 242, 202)'}}>SEO</b> de<br/> votre entreprise.</h3>
            </div>

          </div>
          
        </div>
      </section>

    </div>
  )
}



const Animation = styled.div`
img{
  animation : moveimg 3.5s infinite;
}

@keyframes moveimg{
  0%{ position : relative; bottom : 30px}
  50%{ position : relative; bottom : 0px}
  100%{ position : relative; bottom : 30px}
}

`